modLoader = "javafml"
loaderVersion = "*"
license = "${modLicense}"
issueTrackerURL = "${modGitHub}/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "assets/efs/icon.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/easyfind"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${minMinecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[${yaclVersion},)"
ordering = "NONE"
side = "BOTH"